import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<header>*/}
        {/*  dasdasd*/}
        {/*</header>*/}
        <div>
          {/*<nav>*/}
          {/*  <ul>*/}
          {/*    <li>asd</li>*/}
          {/*    <li>asd</li>*/}
          {/*    <li>asd</li>*/}
          {/*  </ul>*/}
          {/*</nav>*/}

          {children}
        </div>
      </body>
    </html>
  )
}
